spring:
  jackson:
    ## 格式为yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd
    ## 定时区，解决8小时的时间差问题
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#     set @@GLOBAL.sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
    url: jdbc:mysql://192.168.0.211:3306/boyboy
    username: boyboy
    password: xiangjiaochuanmei
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 100000MB

server:
  port: 8085

# 选择api项目下的resouces路径下的user文件夹
# filePath: "/Users/yangyida/Documents/project/complaint_system/web-server/src/main/resources/img/user/"
filePath: "D:/Desktop/System/history/Community/Community-system/core/src/main/resources/img/user/"
#D:\Desktop\System\history\Community\Community-system\core\src\main\resources
# 服务器url路径
projecturl: "http://47.96.226.103:8007"


